public/tradingview.css, src/components/Wallet/WalletConnectButton.tsx, src/components/common/LeverageSlider/index.tsx, src/components/header/ChainSelect.tsx, src/components/header/navigation/mobile/MobileNavigation.tsx, src/components/trade/TradeModule/AssetSelector/AssetOverlay/index.tsx, src/pages/_layout.tsx
- interacting with the navigation elements of the `ChainSelect` now closes the `MobileNavigation`
- starting the wallet connection now cloeses the `MobileNavigation`
- the content behind the `MobileNavigation` is not scrollable anymore
- after selecting a navigation point inside `MobileNavigation` the page is scrolled to the top position
- the chart interactions have been updated. Selecting a custom Symbol or Interval is now permitted. Changing preset intervals is still enabled
- slider thumbs don't have a solid white background anymore
=> Mobile finetuning

src/components/Modals/Account/AccountDeleteModal.tsx, src/components/account/AccountBalancesTable/index.tsx, src/components/account/AccountSummary/index.tsx, src/components/portfolio/Account/Balances.tsx, src/components/portfolio/Account/ManageAccount.tsx, src/components/portfolio/Account/PerpPositions.tsx, src/components/portfolio/Account/Strategies.tsx, src/components/portfolio/Account/Summary.tsx, src/pages/PortfolioAccountPage.tsx, src/pages/V1Page.tsx
- Removed the `Fund Account` Button on empty HLS accounts
- Added buttons to manage an Account in the Portfolio Detail view, if the viewer is the owner of that account
- Refactored the usage of `useAccount` in the portfolio account page
=> Mp 2386 add manage button to portfolio account detail view

src/components/trade/TradeModule/SwapForm/TradeSummary.tsx, src/components/trade/TradeModule/SwapForm/index.tsx
- the `routeInfo` was missing in the `TradeSummary` component
- transaction fees got removed from the `TradeSummary` as they don't matter for the swap/trade summary
=> fix: hotfix TradeSummary

src/chains/neutron/pion-1.ts, src/components/trade/TradeModule/SwapForm/TradeSummary.tsx, src/hooks/trade/useRouteInfo.ts
- Astroport reports price impact via a percent value while Osmosis reports percentage points
- Replaced the routes endpoint for testnet
=> fix: fixed the price impact and trade endpoint of neutron

src/components/account/AccountList/AccountStats.tsx
This PR fixes
- the assets used to calculate the accounts balance inside the `AccountList` component
- the state of the withdraw button to be enabled as soon as a deposit or lend is present in the account
=> Withdraw Button hotfix

src/components/Modals/AssetAmountSelectActionModal.tsx, src/components/Modals/BorrowModal.tsx, src/components/Modals/FundWithdraw/WithdrawFromAccount.tsx, src/components/Modals/LendAndReclaim/index.tsx, src/components/Modals/v1/Borrow.tsx, src/components/Modals/v1/Deposit.tsx, src/components/Modals/v1/Repay.tsx, src/components/Modals/v1/Withdraw.tsx, src/components/account/AccountFund/AccountFundContent.tsx, src/components/account/AccountFund/AccountFundRow.tsx, src/components/common/Slider/index.tsx, src/components/common/TokenInput/TokenInputWithSlider.tsx
This PR removes the debounce on the `TokenInputSlider.`
After testing several scenarios, it became evident that the `debounceFunction` causes significant issues when used in combination with the input field, particularly on the 'TokenInputWithSlider '. 
The simulations did not recognize manual inputs, and moving the slider to 0 or any other value did not represent the correct amount in the updated account simulation. 
Removing the debounce did not harm the dApp's performance, as other improvements that removed some excessive rendering were made in previous pull requests.
This hotfix fixes all issues that the community reported regarding the `TokenInputWithSlider` component.
=> Hotfix Debounce

src/components/Modals/HLS/Deposit/CreateAccount.tsx, src/components/Modals/HLS/Deposit/SelectAccount.tsx, src/components/account/AccountCreateFirst.tsx, src/components/account/AccountMenuContent.tsx, src/hooks/wallet/useAutoLend.ts, src/store/slices/broadcast.ts, src/types/app.d.ts
This PR adds the accountId to the autloendAccountIds Array when creating a new account and activating the lend toggle on the fund account screen.
=> fix: fix autolend on create

src/components/portfolio/Account/Strategies.tsx, src/components/portfolio/Account/Summary.tsx, src/components/portfolio/Card/index.tsx, src/components/portfolio/Overview/Summary.tsx, src/utils/accounts.ts
Updated both the calculation of total balance and networth as well as include the atroport stakedLP like the vaults in osmosis
=> feature: update strategies and balances

src/api/campaign/getCampaignApys.ts, src/utils/parsers.ts, src/utils/resolvers.ts
There was a miscalculation taking place when converting APRs to APYs.
The former math was `APR converted to APY times 100` (if the value wasn't a percentage value)
The correct way is `APR times 100 converted to APY`. This leads to higher values after the calculation but is on-par with how DefiLlama converts APR to APY
=> Fix APY <> APR conversion

src/components/trade/TradeModule/SwapForm/index.tsx
This PR adds the debt amount of the output asset to the deposit cap to prevent users from being blocked to auto-repay debt on an asset that reached its deposit cap.
=> Ignore Debt Amount for Deposit Cap checks on Auto Repay

src/components/account/AccountBalancesTable/Columns/LiqPrice.tsx, src/components/account/AccountDetails/index.tsx, src/components/perps/BalancesTable/Columns/EntryPrice.tsx, src/components/perps/BalancesTable/Columns/Leverage.tsx, src/components/perps/BalancesTable/Columns/Size.tsx, src/components/perps/Module/ExpectedPrice.tsx, src/components/perps/Module/Summary.tsx, src/components/perps/Module/TradingFee.tsx, src/components/portfolio/Overview/Summary.tsx, src/components/trade/TradeChart/index.tsx, src/utils/formatters.ts
Updated price formatting logic to show actual values for small numbers (< $0.01) instead of displaying $0.00. Also created a `getPriceDecimals` function to dynamically calculate needed decimal places and added `showDetailedPrice` prop to `DisplayCurrency` components where appropriate in the Perps modules primarily.
=> feature: add dynamic decimal places

src/chains/neutron/pion-1.ts, src/components/perps/BalancesTable/Columns/Manage.tsx, src/components/perps/BalancesTable/Columns/usePerpsBalancesColumns.tsx, src/components/perps/BalancesTable/index.tsx, src/components/perps/Module/PerpsModule.tsx, src/components/perps/Module/Summary.tsx, src/components/perps/Module/constants.ts, src/components/portfolio/Account/Summary.tsx, src/hooks/perps/usePerpsOrderForm.ts, src/utils/perps.ts
Added stop order functionality by duplicating and inverting limit order logic, ensuring proper price validation based on position direction.
Position flipping safety by automatically cancelling all open limit orders when positions are flipped. 
Added warning dialog when closing positions with active orders.
=> Perps stop order

src/components/Modals/AssetsSelect/index.tsx
This PR fixes the issue of depositing assets when the wallet has deprecated assets in it.
This error changed the indexes of the underlying table, resulting in selected assets disappearing after selection.
=> Asset Deposit Hotfix

src/api/assets/getDexAssets.ts, src/api/assets/getDexPools.ts, src/components/header/Header.tsx
Small fixes from merging perps into develop
- update cached API response
- make trade as default page if no perps (it was deselecting CA when trying to navigate to Trade page)
=> Merge fixes

src/components/header/navigation/Routes.tsx
This commit updates the default route in the Routes component. Instead of rendering the TradePage component as the default route, it now checks the chain configuration and renders either the PerpsPage or the TradePage component accordingly. This change ensures that the correct default page is displayed based on the chain configuration.
=> refactor: Update default route in Routes component

src/components/Modals/AlertDialog/index.tsx, src/components/perps/BalancesTable/Columns/Manage.tsx, src/components/perps/Module/ConfirmationSummary.tsx, src/components/perps/Module/Summary.tsx, src/types/app.d.ts
- moved position label from `Summary` into `ConfirmationSummary`  to prevent confusion of trying to close the modal (when Close label is shown)
- implemented full width button
=> Perps position label

src/components/perps/PerpsTabs.tsx
=> feat: add the subheader to the market stats

src/hooks/managedVaults/useDepositedManagedVaultsFallback.ts, src/hooks/managedVaults/useManagedVaults.ts
This PR includes a 'fallback' deposited vaults when BE api is not working, so users can always see their deposits
=> Always display users deposited vaults

src/api/prices/getOraclePrices.ts
This PR introduces logic that separates assets with a `share` suffix in their denom from other assets before fetching prices from the oracle. These prices are TWAP prices and tend to break since the introduction of duality. TO prevent the UI from being unusable, they are now fetched individually.
=> TWAP price fetching

src/components/earn/farm/perps/PerpsIntro.tsx
- added missing 'unlocking period' for perps vault banner
=> fix: add missing wording

Dockerfile, src/utils/broadcast.ts
This PR fixes including `CancelLimitOrder` events from the duality swap toasts
=> fix: removed unrelated swapping messages

src/components/managedVaults/table/AvailableCommunityVaults.tsx, src/hooks/managedVaults/useManagedVaults.ts
This PR fixes extensive loading when no vaults are available 
- Refetch vaults every 2s if the API returns no funded vaults (TVL < 0), or error -  otherwise every 2 minutes.
- Store and display the last valid set of vaults in a state if the API returns empty or unfunded vaults.
- Show the loading spinner only when there is truly no data to display.
- Removed unnecessary “no vaults” checks in the UI (UI always shows the last valid data or a loading state if it's refetching)
=> Vault fetch fix

src/components/managedVaults/table/column/ActiveBenefits.tsx, src/components/managedVaults/table/useCommunityVaultsColumns.tsx, src/components/managedVaults/vaultDetails/profileVaultCard/InfoRow.tsx, src/components/managedVaults/vaultDetails/profileVaultCard/ProfileVaultCard.tsx, src/components/staking/TierLabel.tsx, src/hooks/managedVaults/useManagedVaults.ts
This PR adds staking information to the vaults overview. This will help users identify vaults with very low trading fees.
=> Add staking tiers to vaults
