mars-protocol/mars-v2-frontend

- src/components/Modals/BorrowModal.tsx
> Hotfix borrow

- src/components/common/Table/Row.tsx
- src/components/perps/BalancesTable/Columns/PnL.tsx
- src/components/perps/BalancesTable/Columns/Size.tsx
- src/components/perps/BalancesTable/usePerpsBalancesData.ts
- src/components/perps/Module/PerpsModule.tsx
- src/components/perps/Module/Summary.tsx
- src/components/perps/PerpsChart.tsx
- src/components/perps/PerpsInfo/index.tsx
- src/components/trade/TradeChart/index.tsx
- src/hooks/perps/usePerpsDenomStates.ts
- src/hooks/perps/usePerpsParams.ts
- src/hooks/useHealthComputer.tsx
- src/pages/PerpsPage.tsx
Addressed the following:
**Bugs**
1. Leverage < 1 on short positions
2. Update `LeverageSlider` when adjusting the input amount
3. Enable positions on multiple assets
**Improvements:**
1. Moved the `PerpsInfo` (OI, funding rate) into the chart header
2. Removed whitespace above summary in `PerpsModule`
4. Added asset value to `PerpsTable`
5. Aligned columns for tables
6. Renamed "Unrealized fees" to "Unrealized Closing Fees"
> Perps alpha fixes

- src/store/slices/broadcast.ts
- this PR removes the MEMO for ledger users
> Hotfix: ledger

- package.json
- src/components/Modals/Modal.tsx
- src/components/Modals/Settings/SettingsOptions.tsx
- src/components/Modals/Settings/index.tsx
- src/components/Wallet/WalletConnectProvider.tsx
- src/components/common/TextInput.tsx
- src/constants/localStorageKeys.ts
- src/hooks/chain/useChainConfig.ts
- src/utils/middleware.ts
- yarn.lock
- added custom RPC and REST endpoints to the settings modal
- added validation for the endpoints
- created TextInput component with error messages
> Custom endpoints

- src/components/trade/TradeModule/SwapForm/index.tsx
- src/components/trade/TradeModule/index.tsx
- `useChainConfig` was causing infinite dependency updates in this construct
> Hofix: node spam on trade

- src/components/header/OracleResyncButton.tsx
- src/store/slices/broadcast.ts
- src/types/app.d.ts
Fixed the functionality of the resync button, by renaming the store function (which had a conflict with a settings key)
> fix: resync button

- src/hooks/health-computer/useHealthComputer.ts
- Use the `liquidation_health_factor` instead of the `max_ltv_health_factor` for the displayed health
> Health Factor adjustments

- src/components/hls/Farm/Table/Columns/Deposit.tsx
- HLS modals didn't open because it was setting undefined values
> Hotfix HLS modal

- src/components/Modals/Account/AccountDeleteModal.tsx
- src/hooks/assets/useAsset.ts
- src/utils/accounts.ts
- Fixed `useAsset` by removing the `useMemo` to avoid empty returns on updated assets return
- Fixed the `isAccountEmpty` check by making all positions optional
- Fixed the `DeleteCreditAccount` modal reporting by setting it to null after clicking delete.
> Fix several small issues

- src/components/Modals/AddFarmAssets/AddFarmAssetsModalContent.tsx
- src/components/Modals/WalletAssets/WalletAssetsModalContent.tsx
- src/components/trade/TradeModule/AssetSelector/AssetList.tsx
- src/components/trade/TradeModule/AssetSelector/AssetOverlay/index.tsx
- src/components/trade/TradeModule/AssetSelector/PairsList.tsx
- Added a wrapper to the `AssetList` component, that fixes the display issues when a search returns only a few results
> Enhance asset list

- src/components/Modals/AstroLp/index.tsx
- src/components/Modals/Farm/FarmDeposits.tsx
- src/components/Modals/Farm/FarmModalContent.tsx
- src/components/Modals/Vault/index.tsx
- src/components/common/Slider/index.tsx
- src/hooks/vaults/useVaultConfigs.tsx
- removed a lot of rerenders by updating dependencies and misusage of `function` definitions. This was necessary because the AstroportLPDeposit Modal rerendered on any change of the slider.
> Fix farm slider

- src/api/campaign/getCampaignApys.ts
- src/chains/neutron/neutron-1.ts
- src/chains/neutron/pion-1.ts
- src/chains/osmosis/osmosis-1.ts
- src/components/Modals/AssetAmountSelectActionModal.tsx
- src/components/Modals/AssetsSelect/Columns/Asset.tsx
- src/components/Modals/AssetsSelect/index.tsx
- src/components/Modals/Farm/FarmModalContentHeader.tsx
- src/components/Modals/WalletAssets/index.tsx
- src/components/account/AccountFund/AccountFundRow.tsx
- src/components/borrow/Table/Columns/Name.tsx
- src/components/common/assets/AssetCampaignCopy.tsx
- src/components/earn/farm/common/Table/Columns/Name.tsx
- src/components/earn/lend/Table/Columns/Campaign.tsx
- src/components/earn/lend/Table/Columns/Name.tsx
- src/constants/USDollar.ts
- src/constants/campaigns.tsx
- src/hooks/assets/useAssetsNoOraclePrices.ts
- src/hooks/campaign/useAssetCampaigns.ts
- src/types/app.d.ts
- src/utils/assets.ts
- src/utils/campaign.ts
- tailwind.config.js
This PR adds multi campaign support for assets
> Multi Campaign Support

- src/components/trade/TradeModule/AssetSelector/AssetOverlay/index.tsx
- src/components/trade/TradeModule/SwapForm/index.tsx
- src/hooks/accounts/useUpdatedAccount/index.ts
This PR fixes the `SwapForm` Rerender / Resetting the input amount to zero
> Fix swap form rerender

- src/components/Modals/Farm/FarmModalContentHeader.tsx
- src/constants/wallets.ts
> bugfix: daily apy

- public/reset.css
- public/reset.html
- src/components/error/ErrorBoundary.tsx
- src/pages/ErrorPage.tsx
- src/pages/_layout.tsx
This PR adds a /reset.html to clear the user's localStorage and redirect them to the dApp.
This will help people facing the client-side error page.
> Reset Page

- src/components/header/RewardsCenter/index.tsx
- src/components/header/navigation/mobile/MobileNavigation.tsx
This PR adds the `RewardsCenter` to the mobile navigation of the app
> Rewards Center on mobile

- src/components/Modals/AddFarmAssets/AddFarmAssetsModalContent.tsx
- src/components/Modals/AssetsSelect/Columns/BorrowRate.tsx
This PR adds all borrow enabled assets to the farm `Borrowings` section
> Farm Borrowings

- src/components/Modals/AssetsSelect/index.tsx
- src/components/account/AccountFund/AccountFundRow.tsx
- src/utils/campaign.ts
- yarn.lock
This PR fixes the initial selection state of the Asset Select Modal, which broke during the introduction of whitelisted and nonWhitelisted Assets.
> Asset Select Table Fix

- src/utils/resolvers.ts
This PR implements a deposit cap buffer of 0.5% to enable farm to work even if the caps are filled
> Deposit cap buffer

- src/utils/farm.ts
This PR adds a temporary fix, that only swaps into the primary asset of a LP position to avoid running into filled caps
> Swap into primary asset on farm

- src/utils/farm.ts
This PR undo's the swapping hotfix to farm
> Undo Farm Hotfix

- src/api/assets/getDexAssets.ts
- src/api/assets/getDexPools.ts
- src/api/cosmwasm-client.ts
- src/api/params/getAssetParams.ts
- src/api/prices/getPythPrices.ts
- src/chains/neutron/neutron-1.ts
- src/chains/neutron/pion-1.ts
- src/chains/osmosis/osmosis-1.ts
- src/components/Wallet/WalletConnecting.tsx
- src/components/Wallet/WalletSelect.tsx
- src/components/error/ErrorBoundary.tsx
- src/pages/ErrorApiPage.tsx
- src/pages/ErrorLocalStoreResetPage.tsx
- src/pages/ErrorNodePage.tsx
- src/pages/_layout.tsx
- src/store/slices/common.ts
- src/types/app.d.ts
- src/utils/error.ts
This PR adds a more versatile way of handling errors by enhancing the checks to identify node and api issues for mandatory/critical fetches.
> Error handling

- src/api/prices/getPrices.ts
- src/chains/neutron/neutron-1.ts
- src/chains/neutron/pion-1.ts
- src/chains/osmosis/osmosis-1.ts
- src/components/header/Header.tsx
- src/store/slices/broadcast.ts
- src/types/app.d.ts
This PR disables pyth whenever slinky is enabled
> Use slinky instead of pyth

- src/components/perps/BalancesTable/Columns/Manage.tsx
- src/components/perps/BalancesTable/usePerpsBalancesData.ts
- src/components/perps/Module/PerpsModule.tsx
- src/components/perps/Module/Summary.tsx
- src/store/slices/broadcast.ts
- src/types/app.d.ts
This PR enables the autolending of perps profits
> feat: added autolend

- src/components/Modals/Hls/Manage/Deposit.tsx
- deposit more on HLS without borrowing was not enabling the button
> Hotfix HLS staking

- src/components/perps/Module/PerpsModule.tsx
- src/components/trade/TradeModule/AssetSelector/AssetSelectorPerps.tsx
- src/hooks/health-computer/useHealthComputer.ts
- src/utils/accounts.ts
- src/utils/getPerpsPosition.ts
This PR fixes the health computation on the FE for Perps
> Perps health

- src/chains/osmosis/osmosis-1.ts
This PR removes milkTIA campaign as the API is infinite loading
> MilkTIA api hotfix

- src/components/portfolio/Overview/Summary.tsx
this PR combines all accounts on the portfolio page (HLS and non HLS accounts)
> Chore: Combine Accounts

- src/components/Modals/KeeperFeeModal.tsx
- src/components/common/AssetAmountInput.tsx
- src/components/common/LeverageSlider/index.tsx
- src/components/common/NumberInput.tsx
- src/components/perps/BalancesTable/usePerpsBalancesData.ts
- src/components/perps/Module/PerpsModule.tsx
- src/components/perps/Module/Summary.tsx
- src/components/perps/Module/usePerpsModule.ts
- src/constants/defaultSettings.ts
- src/constants/math.ts
- src/hooks/perps/useTradingFeeAndPrice.ts
- src/types/classes/BNCoin.ts
- Refactored PerpsModule and usePerpsModule: Improved module structure and usage.
- Updated leverage handling: Corrected leverage calculations.
- Updated open perps positions: Adjusted logic for managing open positions.
- Refactored AssetAmountInput: Updated props and logic for handling max amounts.
- Updated LeverageSlider: Added debounced value state and improved debouncing logic.
- Refactored NumberInput: Simplified input change logic and improved formatted amount handling.
> Perps refactor perp module

- src/components/portfolio/Overview/Summary.tsx
- src/utils/accounts.ts
This PR updates the calculation for apr
- we now use this formula (perp position will be added in different PR)
> Combined apr calculation

- src/api/assets/getDexAssets.ts
- src/api/assets/getDexPools.ts
- src/chains/neutron/pion-1.ts
- src/constants/campaigns.tsx
- src/types/app.d.ts
This PR implements the cached API for `pion-1`
> Implement cached API

- src/components/header/navigation/desktop/NavLink.tsx
- src/components/perps/PerpsInfo/FundingRate.tsx
- perps set as main page when navigating through logo click
- updated decimals for funding rate
PS:
- perps on mobile look good
> Perps small fixes

- src/components/Modals/Account/AccountDeleteModal.tsx
- src/components/Modals/AstroLp/AstroLpWithdraw.tsx
- src/components/Modals/Farm/FarmBorrowings.tsx
- src/components/Modals/Hls/Deposit/CreateAccount.tsx
- src/components/Modals/Hls/Deposit/Summary/HlsFarmingSummary.tsx
- src/components/Modals/PerpsVault/index.tsx
- src/components/common/Toaster/index.tsx
- src/components/earn/farm/vault/Table/Columns/VaultWithdraw.tsx
- src/components/earn/farm/vault/VaultUnlockBanner.tsx
- src/utils/broadcast.ts
- src/utils/generateToast.ts
This PR adds a mutation logic to the analysis of successful transactions.
> Mutation logic

- src/components/common/LimitPriceInput.tsx
- src/components/perps/BalancesTable/Columns/Size.tsx
- src/components/perps/Module/PerpsModule.tsx
- src/components/perps/PerpsChart.tsx
- src/components/trade/TradeChart/index.tsx
- src/hooks/perps/usePerpsOrderForm.ts
TLDR: right-click on a price level, and you can see a "Set limit price" that will switch to the limit price tab and set the price to your selected price.
> feature: create limit order from chart using right click

- src/hooks/health-computer/useHealthComputer.ts
This PR fixes the liquidation prices fetches
> Liquidation Prices

- src/components/header/ChainSelect.tsx
- src/hooks/health-computer/useHealthComputer.ts
- src/store/slices/broadcast.ts
- transactions were failing after changing chains, because the assets in the store didn't update propperly
> v2.7.6 hotfixes

- src/components/perps/PerpsInfo/index.tsx
- src/hooks/perps/usePerpsCallbacks.ts
- src/store/slices/common.ts
- src/utils/getCurrentChainId.ts
- set neutron-1 default chain
- reset leverage on direction/asset change
> refactor: set neutron-1 default chain and reset leverage on direction/asset change

- src/components/common/Intro.tsx
- fixed css for perps vault svg to match other tabs
> Small UI fix

- package.json
- src/components/trade/TradeModule/AssetSelector/AssetSelectorPair.tsx
- src/components/trade/TradeModule/AssetSelector/AssetSelectorPerps.tsx
> Current market logo

- src/components/Modals/AssetsSelect/Columns/Asset.tsx
- src/components/Modals/AssetsSelect/Columns/useSingleAssetSelectColumns.tsx
- src/components/Modals/AssetsSelect/SingleAssetSelect.tsx
- src/components/Modals/ModalsContainer.tsx
- src/components/Modals/VaultAssets/VaultAssetsModalContent.tsx
- src/components/Modals/VaultAssets/index.tsx
- src/components/Modals/index.tsx
- src/components/common/Card/index.tsx
- src/components/common/FullOverlayContent.tsx
- src/components/vaults/community/createVault/CreateVaultContent.tsx
- src/components/vaults/community/createVault/VaultInputElement.tsx
- src/components/vaults/community/createVault/index.tsx
- src/components/vaults/community/vaultDetails/index.tsx
- src/hooks/assets/useVaultAssets.tsx
- src/store/slices/modal.ts
- src/types/app.d.ts
An asset select modal was added that supports single asset selection for provided assets.
> feat: added vault asset select

- src/components/Modals/Account/AccountDeleteModal.tsx
- src/components/account/AccountCreateFirst.tsx
- src/components/account/AccountFund/AccountFundContent.tsx
- src/components/account/AccountFund/AccountFundFullPage.tsx
- enhance account deletion navigation
- streamline account creation logic
- add loading to route fetch
> feature: enhance account deletion navigation, streamline account creation logic, add loading to route fetch

- src/components/header/Header.tsx
- src/components/header/navigation/Routes.tsx
- src/pages/IsolatedPage.tsx
- src/pages/_layout.tsx
- src/types/app.d.ts
> Perps Isolated page

- src/components/perps/Module/MarginTypeSelector.tsx
- src/components/perps/Module/PerpsModule.tsx
- src/components/trade/TradeModule/AssetSelector/AssetOverlay/index.tsx
- src/hooks/perps/usePerpsAsset.ts
- perps markets now reset when switching between Cross and USDC accounts
> Isolated perps fixes

- src/components/portfolio/Account/ManageAccount.tsx
Bug fix: 
- funding correct account when navigating from the portfolio page and having different account selected
> Funding correct account

- src/hooks/assets/useAssets.ts
- src/pages/PerpsPage.tsx
- this PR removes the `perps/unil` market from the UI
> Hotfix: remove NIL

- src/components/managedVaults/community/createVault/MintVaultAccount.tsx
- src/types/app.d.ts
- src/utils/broadcast.ts
- fixed flickering message when creating vault
- added vault title to `fund_manager` transactions
> Vault UI fixes

- src/utils/generateToast.ts
- added a separation for error messages related to bridging transactions and markets being low on liquidity
> Update Error messages

- src/components/common/Card/CardWithTabs.tsx
- src/components/common/Table/index.tsx
- src/components/managedVaults/community/vaultDetails/OwnerVaultPosition.tsx
- src/components/managedVaults/community/vaultDetails/VaultPosition.tsx
- src/components/managedVaults/community/vaultDetails/VaultSummary.tsx
- src/components/managedVaults/community/vaultDetails/Withdrawals.tsx
- src/components/managedVaults/community/vaultDetails/common/Overlays/FeeAction.tsx
- src/components/managedVaults/community/vaultDetails/common/PositionInfo.tsx
- src/components/managedVaults/community/vaultDetails/common/VaultStats.tsx
- src/components/managedVaults/community/vaultDetails/index.tsx
- src/components/managedVaults/community/vaultDetails/profileVaultCard/ProfileVaultCard.tsx
- src/components/managedVaults/community/vaultDetails/table/columns/WithdrawButton.tsx
- added my position preview from the owner side 
- owner of the vault is able to deposit/unlock their position 
- when unlocking - withdraw table is added
- asset image is added to clarify in what asset are rewards/deposits
Owner preview: 
User preview:
> My position preview

- src/api/managedVaults/getHistoricalManagedVaults.ts
- src/api/managedVaults/getManagedVaults.ts
- updated managed vaults api calls to use `getUrl()`
> Update API call to include apikey

- src/api/managedVaults/getManagedVaults.ts
- src/components/managedVaults/createVault/index.tsx
- src/components/managedVaults/table/useCommunityVaultsColumns.tsx
- src/components/managedVaults/vaultDetails/performance/chart/PerformanceChartBody.tsx
- fix failing calls
- updated decimals for 18 decimals assets
- fixed table spacing
> Managed vault

- src/components/managedVaults/vaultDetails/performance/VaultMetricsCard.tsx
- src/components/managedVaults/vaultDetails/profileVaultCard/ProfileVaultCard.tsx
- src/hooks/managedVaults/useHistoricalVaultData.ts
- src/hooks/managedVaults/useManagedVaultAge.ts
- fixed share price and apy  in chart
- added missing prefix on performance tab
- added tooltip for APY on profile card and performance tab
> Apy tooltip & chart fix

- src/components/account/AccountPerpPositionTable/Columns/useAccountPerpsColumns.tsx
- src/components/managedVaults/table/column/Apy.tsx
- src/components/managedVaults/vaultDetails/overview/VaultSummary.tsx
This PR
- adds notificaiton count on vaults table
- fixes width of perps table 
- fixes sorting by APY on main table
> Vault table

- src/components/account/AccountFund/AccountFundContent.tsx
- src/components/portfolio/Overview/AccountsOverview.tsx
Fix: 
- instead of creating and funding new account we fund the existing one
> Fix: funding existing account if no funds

- src/components/managedVaults/vaultDetails/profileVaultCard/ProfileVaultCard.tsx
- src/hooks/managedVaults/useManagedVaultOwnerPosition.ts
This PR adds 
- vault shares of manager for each vault
> Vault owner position

- src/api/swap/getNeutronRouteInfo.ts
- src/components/Modals/Hls/Close/RepayInfo.tsx
- src/components/Modals/Hls/Close/SwapInfo.tsx
- src/components/Modals/Hls/Close/index.tsx
- src/components/Modals/Hls/index.tsx
- src/components/common/AlertDialog/index.tsx
- src/components/common/Toaster/index.tsx
- src/components/managedVaults/vaultDetails/index.tsx
- src/hooks/hls/useHlsCloseStakingPositionActions.ts
- src/hooks/trade/useRouteInfo.ts
- src/pages/VaultsCommunityPage.tsx
- src/utils/broadcast.ts
- src/utils/generateToast.ts
- src/utils/helpers.ts
- src/utils/swap.ts
This PR improves the route fetching for closing HLS by itterating until a satisfactory route result is found
> Hls closing upgrades

- src/components/Modals/BorrowModal.tsx
- src/hooks/accounts/useUpdatedAccount/index.ts
Fixes: 
- simulation when multiple asset selected for repayment
https://github.com/user-attachments/assets/7d227e71-c86b-4ed7-9ec0-dec7bf8665f2
> Fix simulation

- src/api/managedVaults/getHistoricalManagedVaults.ts
- src/hooks/managedVaults/useHistoricalVaultData.ts
- src/hooks/managedVaults/useManagedVaultAge.ts
- temporary fix, vaults age will be added into API response later in the week
> Fix: vaults age

- src/components/Modals/FundWithdraw/WithdrawFromAccount.tsx
- src/components/common/Select/Option.tsx
- enable withdrawing not tradable assets
> Fix: Withdraw all tokens

- src/components/Modals/FundWithdraw/FundAccount.tsx
- src/components/account/AccountCreateFirst.tsx
- src/components/account/AccountFund/AccountFundContent.tsx
- src/components/account/AccountFund/AccountFundFullPage.tsx
> Create and fund account fix

- src/api/swap/getNeutronRouteInfo.ts
This PR fixes the duality route fetching
> Duality route fix
